### ISSUE TITLE
Error: Cannot find module '../appdirect-express'

### ISSUE THREAD

**Issue by Jan314** [olivercox/appdirect-seed#1]
Hi,
First of all, thanks for this module. I have problem when I try to run this example, when I run I get this error: Error: Cannot find module '../appdirect-express'
I run the "npm install" command in terminal and seems it's all ok but the problem persist.
I don't know what I'm doing wrong.

**Comment by olivercox** [comment]
Hi @Jan314.

Apologies for not picking this up sooner. Did you solve the issue you were having?

**Comment by Jan314** [comment]
Hello @olivercox,
Don't worry, yes I solved the problem, I wrote the absolute route and now works ok.
I have a question, all works very good with the differents calls I recive (subscription_order, subscription_change, subscription_cancel), but when is USER_ASSIGNMENT or USER_UNASSIGNMENT I get  errorCode: UNKNOWN_ERROR message: Not Found
I don't know how to manage this.
Thank you for your help

**Comment by olivercox** [comment]
So my first thought would be to establish if the web hook from app direct is calling the url you expect as the error sounds like it could be a 404.

It's been a while since I worked with it but as I remember you should check the configuration of the user assignment in app direct if that seems correct then try debugging locally to see what route is being called. I remember a product https://ngrok.com being very helpful for debugging the integration locally.

**Comment by Jan314** [comment]
Hello,
Ok I will try debugging with ngrok.com, I didn't know this web and seems very useful.
Thanks again
